### ISSUE TITLE
lissp REPL won't work at all when initialized with a buggy library(and keeps throwing exceptions)

### ISSUE THREAD

**Issue by mjobuda** [gilch/hissp#114] opened 2021-10-01 13:33 UTC
When Initialized like lissp -i mylib.lissp (and suppose there is mistake in mylib) the following happens:

```
...
...
# define
__import__('operator').setitem(
  __import__('builtins').globals(),
  'seperator',
  ('```'))

QzSLASH_QzSTAR_

# Traceback (most recent call last):
#   File "/home/mmm/.local/lib/python3.8/site-packages/hissp/compiler.py", line 491, in eval
#     exec(compile(form, "<Hissp>", "exec"), self.ns)
#   File "<Hissp>", line 1, in <module>
# NameError: name 'QzSLASH_QzSTAR_' is not defined
# 
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(LisspREPL)
#>
```

It boots, that's ok. Now do whatever proper operation and while the Lissp interpreter seems to work the code won't get into python and throws exceptions:
```

#> 7
(7)
Traceback (most recent call last):
  File "/home/mmm/.local/lib/python3.8/site-packages/hissp/__main__.py", line 48, in _interact
    repl.lissp.compile(code)
  File "/home/mmm/.local/lib/python3.8/site-packages/hissp/reader.py", line 384, in compile
    return self.compiler.compile(hissp)
  File "/home/mmm/.local/lib/python3.8/site-packages/hissp/compiler.py", line 111, in compile
    sys.exit(1)
SystemExit: 1


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/home/mmm/.local/lib/python3.8/site-packages/hissp/repl.py", line 34, in runsource
    source = self.lissp.compile(source)
  File "/home/mmm/.local/lib/python3.8/site-packages/hissp/reader.py", line 384, in compile
    return self.compiler.compile(hissp)
  File "/home/mmm/.local/lib/python3.8/site-packages/hissp/compiler.py", line 111, in compile
    sys.exit(1)
SystemExit: 1
#>

```
The misbehaviour could be reproduced and repeated.
Expected behaviour would be one of the following:
1) inform the user about the syntax error in the library but keep going on with the part of the library that is OK
2) Drop the library and continue with normal repl
3) exit
In the current situation a nonusable repl is started.

**Comment by mjobuda** [comment] 2021-10-01 13:48
Version is hissp-0.3.0a0

**Comment by gilch** [comment] 2021-10-02 00:06
Version number only helps for releases. I would need the git hash to know your exact revision for an alpha, but it's best to just update to the latest master instead of both of us wasting time trying to find that. It looks like you're slightly behind the current master. Force an update, and if this is still happening, try to make an extremely small script that still reproduces the error, and reply with the exact code from that so I can try to debug it. I haven't seen this happen before.

**Comment by gilch** [comment] 2021-10-02 00:17
I think I might know what's happening from that traceback. The abort state is getting set in the compiler. This only happens in the main module. This is to prevent any further code from executing after a terminal exception, because the script might do something dangerous in a bad state. It seems the REPL is reusing the same compiler for interactive mode, but catching the system exit, which is making it try to abort again for every new loop. There's no reason to think the REPL entries are dangerous since they're under user control. The remainder of the script should have already been aborted by the first sys exit and it might be helpful for debugging to have a working REPL with the state from the first part. I think I can fix this by resetting the abort state just before the exit. The first abort will still happen, but then it will no longer be in the abort state if the REPL takes over. I'll try that.

**Comment by gilch** [comment] 2021-10-02 00:35
I'm pretty sure I reproduced your error and fixed it. Install the fix branch with

    pip install -U git+https://github.com/gilch/hissp@abort-reset

and confirm for me, so I can close this.

**Comment by gilch** [comment] 2021-10-02 03:07
My script was
```
(hissp.basic.._macro_.prelude)
(define spam 42)
(truediv 1 0)
```
I confirmed `spam` was present after the crash with the fix.

**Comment by mjobuda** [comment] 2021-10-02 11:44
Confirm. Behaves properly now.

**Closed** 2021-10-02 15:29 UTC
